services:
  flask-app:
    build: .
    ports:
      - "7000:5000"
    restart: always
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    command: flask run --host=0.0.0.0 --port=5000 --cert=cert.pem --key=key.pem
